//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Minesweeper Game, a copy of the standard Windows game. This is a puzzle - you should clear a minefield. By hints you should figure out landmines location and mark them. You can choose the level of difficulty from a beginner to an expert or create your own game. This application is completely free and doesn&apos;t contain any advertising..
        /// </summary>
        public static string ADescription {
            get {
                return ResourceManager.GetString("ADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puzzle,landmine,logic,flag,number.
        /// </summary>
        public static string AKeywords {
            get {
                return ResourceManager.GetString("AKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Minesweeper Game.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minesweeper.
        /// </summary>
        public static string ATitle1 {
            get {
                return ResourceManager.GetString("ATitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Minesweeper.
        /// </summary>
        public static string ATitle2 {
            get {
                return ResourceManager.GetString("ATitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lazy Minesweeper.
        /// </summary>
        public static string ATitle3 {
            get {
                return ResourceManager.GetString("ATitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champions.
        /// </summary>
        public static string ChampionsPageTitle {
            get {
                return ResourceManager.GetString("ChampionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LazyPenguin Studio.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations !!!.
        /// </summary>
        public static string Congratulation {
            get {
                return ResourceManager.GetString("Congratulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graphic designer.
        /// </summary>
        public static string designer {
            get {
                return ResourceManager.GetString("designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fernando Castilio.
        /// </summary>
        public static string DesignerName {
            get {
                return ResourceManager.GetString("DesignerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to developer.
        /// </summary>
        public static string developer {
            get {
                return ResourceManager.GetString("developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evgeny Freyman.
        /// </summary>
        public static string DeveloperName {
            get {
                return ResourceManager.GetString("DeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        public static string EnterNamePhrase {
            get {
                return ResourceManager.GetString("EnterNamePhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to leave the game?.
        /// </summary>
        public static string ExitQuestion {
            get {
                return ResourceManager.GetString("ExitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a classic minesweeper game. The rules are the same as in the standard windows minesweeper game, but control differs. Full description of rules is available on the start page (shift the screen to the right)..
        /// </summary>
        public static string HelpMessage_line1 {
            get {
                return ResourceManager.GetString("HelpMessage_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To uncover a cell - hold a finger on the cell for some time. The game starts as soon as the first cell is uncovered..
        /// </summary>
        public static string HelpMessage_line2 {
            get {
                return ResourceManager.GetString("HelpMessage_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To put a flag - tap a finger on the cell..
        /// </summary>
        public static string HelpMessage_line3 {
            get {
                return ResourceManager.GetString("HelpMessage_line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use mine detector - tap a finger on the number around which you want to uncover cells. Remember that it is safe only if every flag around this number is correct..
        /// </summary>
        public static string HelpMessage_line4 {
            get {
                return ResourceManager.GetString("HelpMessage_line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfortable playing suppose using mine detector as often as possible and uncovering cells by holding a finger very rarely..
        /// </summary>
        public static string HelpMessage_line5 {
            get {
                return ResourceManager.GetString("HelpMessage_line5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good luck.
        /// </summary>
        public static string HelpMessage_line6 {
            get {
                return ResourceManager.GetString("HelpMessage_line6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmines.
        /// </summary>
        public static string landmines {
            get {
                return ResourceManager.GetString("landmines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        public static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string levelx {
            get {
                return ResourceManager.GetString("levelx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops!.
        /// </summary>
        public static string ooops {
            get {
                return ResourceManager.GetString("ooops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string rules {
            get {
                return ResourceManager.GetString("rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object:.
        /// </summary>
        public static string Rules_line1 {
            get {
                return ResourceManager.GetString("Rules_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Study the patterns. If three squares in a row display 2-3-2, then you know three landmines are probably lined up beside that row. If a square says 8, every surrounding square is mined..
        /// </summary>
        public static string Rules_line10 {
            get {
                return ResourceManager.GetString("Rules_line10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Explore the unexplored. Not sure where to click next? Try clearing some unexplored territory. You&apos;re better off clicking in the middle of unmarked squares than in an area you suspect is mined..
        /// </summary>
        public static string Rules_line11 {
            get {
                return ResourceManager.GetString("Rules_line11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Find the empty squares while avoiding the mines. The faster you clear the board, the better your score..
        /// </summary>
        public static string Rules_line2 {
            get {
                return ResourceManager.GetString("Rules_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play:.
        /// </summary>
        public static string Rules_line3 {
            get {
                return ResourceManager.GetString("Rules_line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Uncover a landmine, and the game ends..
        /// </summary>
        public static string Rules_line4 {
            get {
                return ResourceManager.GetString("Rules_line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Uncover an empty square, and you keep playing..
        /// </summary>
        public static string Rules_line5 {
            get {
                return ResourceManager.GetString("Rules_line5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Uncover a number, and it tells you how many landmines lay hidden in the eight surrounding squares-information you use to deduce which nearby squares are safe to open..
        /// </summary>
        public static string Rules_line6 {
            get {
                return ResourceManager.GetString("Rules_line6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints and tips:.
        /// </summary>
        public static string Rules_line7 {
            get {
                return ResourceManager.GetString("Rules_line7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Mark the landmines. If you suspect a square conceals a mine, tap it. This puts a flag on the square..
        /// </summary>
        public static string Rules_line8 {
            get {
                return ResourceManager.GetString("Rules_line8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Use mine detector. If you are sure about every flag around a number, tap it and this uncover all cells around this number.
        /// </summary>
        public static string Rules_line9 {
            get {
                return ResourceManager.GetString("Rules_line9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound effects.
        /// </summary>
        public static string soundEffects {
            get {
                return ResourceManager.GetString("soundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a problem :(.
        /// </summary>
        public static string UnhandledMessage_line1 {
            get {
                return ResourceManager.GetString("UnhandledMessage_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t worry, the report was already sent to developers and now they are working hard in order to fix this issue :).
        /// </summary>
        public static string UnhandledMessage_line2 {
            get {
                return ResourceManager.GetString("UnhandledMessage_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are really angry, please email here:.
        /// </summary>
        public static string UnhandledMessage_line3 {
            get {
                return ResourceManager.GetString("UnhandledMessage_line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is impossible to create a game with these parameters.
        /// </summary>
        public static string WrongParamsMessage {
            get {
                return ResourceManager.GetString("WrongParamsMessage", resourceCulture);
            }
        }
    }
}
